--- #Connection Block
-name: install packages
  host: mariadb
  become: true
  become_method: sudo
  user: ec2-user
  tasks:
    #Task Block
   - name: Install mariadb
     ansible.builtin.package:
        name: mariadb
        state: present
